import { Product, Review } from '@/types/database';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'litef Pro X Wireless Kulaklık',
    description: 'Hibrit Aktif Gürültü Engelleme (ANC), 48 saat pil ömrü, uzamsal ses ve 40mm berilyum sürücüler.',
    price: 3499,
    original_price: 4899,
    rating: 4.9,
    reviews_count: 142,
    category: 'Kulaklık & Ses',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    badge: 'Lansman Özel',
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Aura Chrono Ultra Akıllı Saat',
    description: 'Havacılık sınıfı titanyum gövde, safir cam, EKG & kan oksijeni takibi ve 14 güne varan pil ömrü.',
    price: 4999,
    original_price: 6200,
    rating: 4.8,
    reviews_count: 98,
    category: 'Akıllı Saatler',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    badge: 'Yeni Nesil',
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Vortex Vision XR Sanal Gözlük',
    description: 'Çift 4K Mikro-OLED ekran, entegre göz ve el takibi, 120Hz yenileme hızı ve uzamsal ses mimarisi.',
    price: 12899,
    original_price: 15400,
    rating: 5.0,
    reviews_count: 54,
    category: 'Giyilebilir Teknoloji',
    image_url: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80',
    badge: 'Sınırlı Üretim',
    in_stock: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'SonicPulse Studio Masaüstü Hoparlör',
    description: '120W RMS güç çıkışı, ahşap akustik kabin, Bluetooth 5.3 ve optik yüksek çözünürlüklü giriş.',
    price: 2199,
    original_price: 2800,
    rating: 4.7,
    reviews_count: 86,
    category: 'Kulaklık & Ses',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    badge: 'Çok Satan',
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'MagCharge Pro 3-in-1 Kablosuz İstasyon',
    description: 'Telefon, saat ve kulaklığı aynı anda 15W hızlı şarj edebilen alüminyum katlanabilir şarj standı.',
    price: 999,
    original_price: 1450,
    rating: 4.9,
    reviews_count: 110,
    category: 'Aksesuarlar',
    image_url: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800&auto=format&fit=crop&q=80',
    badge: '%30 İndirim',
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'CyberKey RGB Manyetik Mekanik Klavye',
    description: '0.1mm hassasiyetli hall-effect manyetik switchler, CNC alüminyum gövde ve dinamik RGB aydınlatma.',
    price: 2650,
    original_price: 3200,
    rating: 4.8,
    reviews_count: 73,
    category: 'Aksesuarlar',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    badge: 'Oyuncu Serisi',
    in_stock: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Murat Kara',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    date: '2 gün önce',
    comment: 'litef Pro X kulaklığı lansman gününde aldım. Gürültü engellemesi uçakta denedim, dünya sesini sıfıra indiriyor. Malzeme kalitesi inanılmaz.',
    product_name: 'litef Pro X Wireless',
  },
  {
    id: 'rev-2',
    author: 'Selin Aydın',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    date: '1 hafta önce',
    comment: 'Aura Chrono saatimin pili gerçekten 12-14 gün gidiyor. Titanyum gövde bilekte çok asil duruyor, kargo ertesi gün kapımdaydı.',
    product_name: 'Aura Chrono Ultra',
  },
  {
    id: 'rev-3',
    author: 'Emre Yılmaz',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    date: '2 hafta önce',
    comment: 'Vortex Vision XR gözlük ile uzamsal çalışma ortamı kurdum. Çözünürlük pikselleri sayamayacağınız kadar net. Teknoloji harikası.',
    product_name: 'Vortex Vision XR',
  },
];

export const CATEGORIES = [
  'Tümü',
  'Kulaklık & Ses',
  'Akıllı Saatler',
  'Giyilebilir Teknoloji',
  'Aksesuarlar',
];
